<?php

namespace Duf\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DufAdminNestedTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DufAdminNestedTreeRepository extends EntityRepository
{
    public function findByParentId($entity_name, $parent_id = null)
    {
        $qb 		= $this->_em->createQueryBuilder()
                         		->select('category')
                         		->from($entity_name, 'category');

        if (null !== $parent_id) {
        	$qb->leftJoin($entity_name, 'parent_category', 'WITH', 'parent_category.id = category.parent')
        	   ->where('parent_category.id = :parent_id')
        	   ->setParameter('parent_id', $parent_id);
        }
        else {
        	$qb->where('category.root IS NOT NULL');
        }

        return $qb->getQuery()->getResult();
    }

    public function getCategoriesArray($entity_name)
    {
        $qb     = $this->_em->createQueryBuilder()
                            ->select('category')
                            ->from($entity_name, 'category');

        return $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
