<?php

namespace Duf\AdminBundle\Entity\Repository;

/**
 * ExportDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExportDataRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByExportEntities($entity_name, $items_ids)
	{
        return $this->_em->createQueryBuilder()
                         ->select('u')
                         ->from($entity_name, 'u')
                         ->where('u.id IN (:items_ids)')
                         ->setParameter('items_ids', $items_ids)
                         ->getQuery()
                         ->getResult();
	}
}
