<?php

namespace Duf\Bundle\AdminBundle\Entity\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHeaderTasks($user, $limit)
	{
        return $this->_em->createQueryBuilder()
        				 ->select('task')
        				 ->from($this->_entityName, 'task')
        				 ->where('task.user = :user')
                         ->andWhere('task.progress < 100')
        				 ->setParameter('user', $user)
        				 ->setMaxResults($limit)
        				 ->getQuery()
        				 ->getResult();
	}
}
